//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientWCF.ServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IHotel")]
    public interface IHotel {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHotel/GetAllHotels", ReplyAction="http://tempuri.org/IHotel/GetAllHotelsResponse")]
        HotelApplicationWCF.Hotel[] GetAllHotels();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHotel/GetAllHotels", ReplyAction="http://tempuri.org/IHotel/GetAllHotelsResponse")]
        System.Threading.Tasks.Task<HotelApplicationWCF.Hotel[]> GetAllHotelsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHotel/GetHotelById", ReplyAction="http://tempuri.org/IHotel/GetHotelByIdResponse")]
        HotelApplicationWCF.Hotel GetHotelById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHotel/GetHotelById", ReplyAction="http://tempuri.org/IHotel/GetHotelByIdResponse")]
        System.Threading.Tasks.Task<HotelApplicationWCF.Hotel> GetHotelByIdAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHotelChannel : ClientWCF.ServiceReference.IHotel, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HotelClient : System.ServiceModel.ClientBase<ClientWCF.ServiceReference.IHotel>, ClientWCF.ServiceReference.IHotel {
        
        public HotelClient() {
        }
        
        public HotelClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HotelClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HotelClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HotelClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public HotelApplicationWCF.Hotel[] GetAllHotels() {
            return base.Channel.GetAllHotels();
        }
        
        public System.Threading.Tasks.Task<HotelApplicationWCF.Hotel[]> GetAllHotelsAsync() {
            return base.Channel.GetAllHotelsAsync();
        }
        
        public HotelApplicationWCF.Hotel GetHotelById(int id) {
            return base.Channel.GetHotelById(id);
        }
        
        public System.Threading.Tasks.Task<HotelApplicationWCF.Hotel> GetHotelByIdAsync(int id) {
            return base.Channel.GetHotelByIdAsync(id);
        }
    }
}
